### ISSUE TITLE
Restrict usage to specific roles

### ISSUE THREAD

**Issue by kfeeken** [HSG-Library/alma-copy-user-roles#8]
Hello,

This app is great and I use it quite a bit when assigning user roles to new staff members.  However, I discovered that there doesn't seem to be any limitations based on the roles of the person using it.  It seems that anyone can use it regardless of the roles they have.  Just curious if there was any thought to limiting usage based on the role of the person using the app (i.e. only users with User Administrator or User Manager role can use it)?

Thanks,
Kevin

**Comment by d22** [comment]
Hello Kevin
According to ExLibris documentation, a user cannot allow more than their roles in a CloudApp:

> "APIs called by the Rest Service are executed in the context of the logged-in user. The user must have permission to perform the action implemented by the API, and all history actions are logged under the user's identity."

 (see: https://developers.exlibrisgroup.com/cloudapps/docs/api/rest-service/)

I'm going to look at this anyway, as the desire for the ability to restrict functionality has come up several times.

Jonas

**Comment by Raphael-Rey** [comment]
Hello Jonas,

Currently it isn't possible to rely on Alma to do this check: you have really to test explicitely if the user has enough rights.

I wrote to Ex Libris to announce this problem, but if they make a fix, it will not be very quick, I fear.

I have no experience myself with cloud app development, but maybe you could require an api key in the configuration and use this api key to check the users roles.

Now some libraries forbid the use of the application and allow it just the time to make the changes.

Best regards

Raphaël

**Comment by d22** [comment]
Hi Raphaël
Thank you for your tests. Since there were multiple reports of this permission issue, I assumed that this - even though stated otherwise in the documentation - does not work.

I am currently working on a solution for this issue in this CloudApp. I will update this thread as soon as I have a working solution.

br
Jonas

**Comment by d22** [comment]
Hi @kfeeken, @Raphael-Rey  and @mschwendener

I just released a new version, which adds the possibility to restrict app-access by user or by some roles. (Should be available soon).

Since ExLibris does not provide an environment to deploy CloudApps other than on production or single local machines, I'd like to ask you if could support me, by testing the new feature. 
I tested locally on my machine during development and I am quite confident, that the new release wont break anything. 

There is a short documentation in the [README.md](https://github.com/HSG-Library/alma-copy-user-roles)

Please report if something does not work, or if something needs improvement.

br 
Jonas

**Comment by Raphael-Rey** [comment]
Hello @d22 ,

Thank you for this new feature.

Did you deploy the new version on Ex Libris server? or would you like that we test it locally?

Best regards,

Raphaël

**Comment by d22** [comment]
Hi @Raphael-Rey 

I wanted to release to production, but the release was currently rejected. Just fyi I opened a topic about this in the ExLibris Forum: https://developers.exlibrisgroup.com/?post_type=topic&p=73212

So, if you can test it locally, I would appreciate it, otherwise I will tell you when it ist available in production so you can test there. 

Thank you, br
Jonas

**Comment by d22** [comment]
The new version (v1.1.1) is now available in the productive Alma environment. 

cc: @Raphael-Rey, @kfeeken, @mschwendener

**Comment by Raphael-Rey** [comment]
Thank you Jonas,

I tried it and it seems to work. Giving the possibility to filter by user or by role goes far beyond what one could expect. I'm just not fan of your icons to select/deselect all rows. Without testing it, we cannot understand what it does. The position is not great too (I know it is not always simple to change that in this framework). The arrows shows a more "normal" place for this kind of feature. Maybe only one button is enough.

![2022-06-07 17_45_02-Ex Libris - Alma](https://user-images.githubusercontent.com/99899683/172550158-8496f15f-cbab-4e5e-86e1-18139be077fb.png)

Apart from this detail, it is really a great work.

Thank you very much.

Best regards,

Raphaël

**Comment by d22** [comment]
Hi @Raphael-Rey 
Thank you for the feedback! I created a new issue for the optimisations regarding icons: #13 
I will close this issue, since the usage restriction feature seem to work. 

br
Jonas

Feature implemented in #10
